penguins = ["King", "Emperor", "Chinstrap", "Gentoo", "Little", "African", "Southern Rockhopper", "Macaroni"]
pHab = ["King penguins spend a lot of time in the ocean feeding,\n but their primary habitats are sparsely vegetated areas of islands in the southern oceans and sub-Antarctic\n", "Wild Emperor penguins are only found in Antarctica. They breed and raise their young mostly on 'fast ice', a floating platform of frozen ocean which is connected to the land or to ice shelves.", "Chinstrap penguins breed mainly on the Antarctic Peninsula and on islands in the South Atlantic Ocean. There is a small breeding population on the Balleny Islands, south of New Zealand.", "Gentoo penguins have a large geographic range. They breed on many sub-Antarctic islands and on the Antarctic Peninsula. They generally occupy their islands all year round. The largest populations of gentoo penguins are in the Falkland Islands (South Georgia), and on the Antarctic Peninsula.", "The Little Penguin occurs only in Australia and New Zealand. They are found right along the southern edge of Australia and Tasmania. Most colonies exist on islands such as Kangaroo Island and Phillip Island. The breeding season runs from August to February.", "African penguins are found along coastal areas and offshore islands. Their preferred habitats are flat sandy areas with sparse oThese penguins live on rocky shorelines and make burrows and nests in high grasses called tussocks, they live among the craggy, windswept shorelines of the islands north of Antarctica, from Chile to New Zealand.", "Macaroni penguins live in rocky, water-bound areas, on rocks and cliffs above the ocean, and can be found on sub–Antarctic Islands and, occasionally, on the northwestern Antarctic Peninsula and its adjacent islands"]
pDiet = ["King penguins are quite specialised in their prey. They mainly eat lantern fish (myctophids), especially during the breeding season. Over winter, the percentage of squid in their diet increases.", "Emperors feed mostly on Antarctic silverfish as well as other species of fish, krill and some squid. An adult penguin eats about 2-3 kg per day, but on a good day they can eat twice this much to build up their store of body fat for the long winter, or for feeding their chicks.", "Chinstrap penguins feed mainly on krill and fish and are considered near-shore feeders, feeding close to their breeding colonies. They catch prey by pursuit-diving using their flippers to 'fly' through the water.", "Gentoo penguins are opportunistic hunters. Their diet is quite diverse and varies with season and location. They usually eat a mix of crustaceans, small fishes and squid.", "Little penguins feed on small fish, squid and krill (tiny shrimp-like crustaceans). They mainly feed in shallow waters within 15 to 20 kilometres of the coast. They hunt near the surface for fish such as pilchards, anchovies and garfish.", "African penguins feed on 25 species of fish, such as sardine and anchovy but also prey on squid and krill.", "Rockhoppers primarily eat krill, but will also eat other crustaceans as well as squid.", "This penguin feeds mainly on krill, but will also eat other crustaceans, small fish, and squid."]
pApp = ["The king penguin has a black head, chin, and throat, with vivid orange, tear-shaped patches on each side of the head. The orange coloration extends to the upper chest.", "Emperor penguins are the largest sea birds in the Antarctic, standing 101 to 132 cm tall. They have wingspans ranging from 76 to 89 cm. These penguins have black and white bodies with stiff black wings. Their back, head, chin, throat, and the dorsal parts of their wings are black.", "Medium-sized penguin with black head and white face. A black stripe under the chin distinguishes the species. Chinstraps are one of three species of brush-tail penguins along with the Adélie and gentoo penguins.", "Gentoo penguins have orange-red bills and feet that set them apart from their close relatives, the Adélies and chinstraps. Gentoos also have a white cap extending from eye to eye over the top of their heads.", "This penguin grows to be about 26.5 to 27.5 inches tall and weighs between 4.4 and 11 pounds. It has a black stripe and a pattern of unique black spots on its chest, as well as pink glands above its eyes that become pinker as the penguin gets hotter. Males are larger than females and have larger beaks.", "This penguin grows to be about 26.5 to 27.5 inches tall and weighs between 4.4 and 11 pounds. It has a black stripe and a pattern of unique black spots on its chest, as well as pink glands above its eyes that become pinker as the penguin gets hotter. Males are larger than females and have larger beaks.", "Southern rockhopper penguins have white fronts and black heads and hoods. Their beaks are bright orange, and their eyebrows are bright yellow. At the outer edge of the eyebrows, long yellow feathers extend off the sides of the head.", "The macaroni penguin averages about 20 to 28 inches in length and about 11 pounds in weight. It has black upperparts, white underparts, and distinctive yellow and black plumes on the top of its head. This species closely resembles the royal penguin, but has a black chin rather than a white one."]
pConStat = ["The International Union for Conservation of Nature (IUCN) lists king penguins as a species of Least Concern.", "The International Union for Conservation of Nature (IUCN) lists emperor penguins as a species Near Threatened", "The International Union for Conservation of Nature (IUCN) lists chinstrap penguins as a species of Least Concern" "The International Union for Conservation of Nature (IUCN) lists gentoo penguins as a species Near Threatened", "The International Union for Conservation of Nature (IUCN) lists little penguins as a species of Least Concern", "The International Union for Conservation of Nature (IUCN) lists african penguins as a species Endangered", "The International Union for Conservation of Nature (IUCN) lists southern rockhopper penguins as a species Vulnerable", "The International Union for Conservation of Nature (IUCN) lists macaroni penguins as a species Vulnerable"]
p = input("Hello! Welcome to Penguin Facts! What Penguin would you like to learn about?\n0. King\n1. Emperor\n2. Chinstrap\n3. Gentoo\n4. Little\n5. African\n6. Southern Rockhopper\n7. Macaroni\n")
i = input("What do you want to learn about the " + penguins[int(p)] + " Penguin?\n0. Habitat\n1. Diet\n2. Appearance\n3. Conservation Status\n")
if i == "0":
    print(pHab[int(p)])
elif i == "1":
    print(pDiet[int(p)])
elif i == "2":
    print(pApp[int(p)])
elif i == "3":
    print(pConStat[int(p)])